// <auto-generated />
using System;
using BAR.Modules.Betrieb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BAR.Modules.Betrieb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BetriebDbContext))]
    [Migration("20260911154131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("betrieb")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BAR.Modules.Betrieb.Domain.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BazaarFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bazaar_from");

                    b.Property<DateTime?>("BazaarUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bazaar_until");

                    b.Property<int>("BlockSize")
                        .HasColumnType("integer")
                        .HasColumnName("block_size");

                    b.Property<int>("DefaultBlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("default_block_count");

                    b.Property<string>("DefaultTypeId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("default_type_id");

                    b.Property<DateTime?>("DropOffFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_off_from");

                    b.Property<DateTime?>("DropOffUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_off_until");

                    b.Property<string>("InfoText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("info_text");

                    b.Property<DateTime?>("RegistrationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_deadline");

                    b.Property<int>("StartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("start_number");

                    b.HasKey("Id");

                    b.ToTable("settings", "betrieb");
                });
#pragma warning restore 612, 618
        }
    }
}
