<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

  <!-- Aggregate und Domain-Services werden ohne Mocks getestet. -->
  <ItemGroup>
    <ProjectReference Include="..\..\BAR.Domain\BAR.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
  </ItemGroup>

</Project>
