// <auto-generated />
using System;
using BAR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BAR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BarDbContext))]
    [Migration("20260910160027_MakeSettingsFieldsNullable")]
    partial class MakeSettingsFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BAR.Domain.Articles.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("seller_id");

                    b.Property<string>("Size")
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("seller_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.MasterData.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Original")
                        .HasColumnType("boolean")
                        .HasColumnName("original");

                    b.HasKey("Id");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.MasterData.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Original")
                        .HasColumnType("boolean")
                        .HasColumnName("original");

                    b.HasKey("Id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.NumberBlocks.NumberBlock", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("FromNumber")
                        .HasColumnType("integer")
                        .HasColumnName("from_number");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("seller_id");

                    b.Property<int>("ToNumber")
                        .HasColumnType("integer")
                        .HasColumnName("to_number");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("number_block", null, t =>
                        {
                            t.HasCheckConstraint("CK_number_block_range_valid", "\"to_number\" >= \"from_number\"");
                        });
                });

            modelBuilder.Entity("BAR.Domain.SellerTypes.SellerType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("commission_rate");

                    b.Property<decimal>("ItemFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("item_fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("seller_type", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.Sellers.Seller", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text")
                        .HasColumnName("invite_token");

                    b.Property<DateTime?>("InviteTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_token_expires_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("SellerTypeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("seller_type_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("seller", (string)null);
                });

            modelBuilder.Entity("BAR.Domain.Settings.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BazaarFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bazaar_from");

                    b.Property<DateTime?>("BazaarUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bazaar_until");

                    b.Property<int>("BlockSize")
                        .HasColumnType("integer")
                        .HasColumnName("block_size");

                    b.Property<int>("DefaultBlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("default_block_count");

                    b.Property<string>("DefaultTypeId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("default_type_id");

                    b.Property<DateTime?>("DropOffFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_off_from");

                    b.Property<DateTime?>("DropOffUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_off_until");

                    b.Property<string>("InfoText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("info_text");

                    b.Property<DateTime?>("RegistrationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_deadline");

                    b.Property<int>("StartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("start_number");

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
